version: "3.8"
services:
  backend:
    build:
      context: .  # This should point to the directory that contains the backend folder
      dockerfile: Dockerfile-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1

  frontend:
    build:
      context: .  # This should point to the directory that contains the frontend folder
      dockerfile: Dockerfile-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
