FROM python:3.8

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app


# You might need to adjust the paths in these COPY commands
COPY ./backend /app
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . /app/

CMD ["python", "cybersec/manage.py", "runserver", "0.0.0.0:8000"]
