# Use an official Node runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Install app dependencies
COPY ./frontend ./
RUN npm install


# Build the app
RUN npm run build

# # Install serve to run the application
# RUN npm install -g serve

# Run the application
# CMD ["serve", "-s", "build", "-l", "3000"]
CMD ["npm","start"]
